<?php

//$Id$

define('APPLICATION_UNIX_NAME', 'inicrond');
define('APPLICATION_MAJOR_VERSION', 3);
define('APPLICATION_MINOR_VERSION', 3);
define('APPLICATION_RELEASE_NUMBER', 0);
define('APPLICATION_EXTRA_VERSION_TEXT', '');
define('APPLICATION_DEVEL_WEB_SITE', 'http://'.APPLICATION_UNIX_NAME.'.sourceforge.net/');

define('APPLICATION_COMPLETE_RELEASE_NAME', APPLICATION_UNIX_NAME.' '.APPLICATION_MAJOR_VERSION.'.'.APPLICATION_MINOR_VERSION.'.'.APPLICATION_RELEASE_NUMBER.APPLICATION_EXTRA_VERSION_TEXT);

?>
