SELECT
start_gmt_timestamp,
end_gmt_timestamp,
adresse_ip,
end_gmt_timestamp-start_gmt_timestamp,
session_id,
OOO_usrs.usr_id,
dns,
usr_name,
HTTP_USER_AGENT
FROM
OOO_online_time,
OOO_usrs
WHERE
OOO_usrs.usr_id=OOO_online_time.usr_id
AND
start_gmt_timestamp>=1070168400
AND
start_gmt_timestamp<1101704400

1103580788